language: cpp

os: linux
sudo: false
dist: trusty

env:
  global:
    - DEVKITPRO=$HOME/devkitPro

cache:
  directories:
    - "$HOME/.local"
    - "/home/travis/portlibrepos"

addons:
  apt:
    packages:
    - p7zip-full

before_install:
  - mkdir -p "${PORTLIBREPOS}"
  - mkdir -p "${DEVKITPRO}"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb -O /tmp/devkitpro-pacman.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i /tmp/devkitpro-pacman.deb; fi
  - yes | sudo dkp-pacman -Syu devkitPPC
  - export DEVKITPPC=/opt/devkitpro/devkitPPC

install:
  - cd $PORTLIBREPOS
  - ((git clone https://github.com/Maschell/dynamic_libs.git -b lib && (7z x -y ./dynamic_libs/libs/portlibs.zip -o${DEVKITPRO})) || (cd dynamic_libs && git pull))
  - (cd dynamic_libs && ((make -j8 | grep -c "built ... ") && make install && echo "installed" ) || (echo "no need for make install" && make))

script:
  - cd "$HOME"
  - make && make install